data:
    dataset: "KAIST"
    image_size: 64
    channels: 3
    num_workers: 32
    data_dir: "./data/" # "data"
    work_dir: "./work_dir/" # "work_dir"
    conditional: True

model:
    in_channels: 156 
    out_ch: 3
    ch: 256
    ch_mult: [1, 2, 3, 4]
    num_res_blocks: 2
    attn_resolutions: [16, ]
    dropout: 0.0
    ema_rate: 0.999
    ema: True
    resamp_with_conv: True

diffusion:
    beta_schedule: linear
    beta_start: 0.0001
    beta_end: 0.02
    num_diffusion_timesteps: 1000

training:
    patch_n: 4
    batch_size: 8
    n_iters: 2000000
    snapshot_freq: 50000
    validation_freq: 50000

sampling:
    batch_size: 4
    last_only: True

optim:
    weight_decay: 0.000
    optimizer: "Adam"
    lr: 0.00002
    amsgrad: False
    eps: 0.00000001
